### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith' Error

### ISSUE THREAD

**Issue by farisoft** [socialbotspy/LinkedinPy#7]
I am getting the following error.

` ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Farath Shba/LinkedinPy"
Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    session = LinkedinPy()  # use_firefox=True)
  File "C:\Users\Farath Shba\Downloads\LinkedinPy-master\linkedinpy\linkedinpy.py", line 148, in __init__
    get_database(Settings, make=True)
  File "C:\Users\Farath Shba\Downloads\LinkedinPy-master\linkedinpy\database_engine.py", line 45, in get_database
    address = validate_database_address(Settings)
  File "C:\Users\Farath Shba\Downloads\LinkedinPy-master\linkedinpy\database_engine.py", line 109, in validate_database_address
    if not address.endswith(".db"):
AttributeError: 'NoneType' object has no attribute 'endswith'`

Is there any resolvement for this?

**Comment by ishandutta2007** [comment]
I haven't tried on windows. Let us know what works for you. Will create a documentation for windows accordingly
